Add stakater-validate-environment 1.0.0
stakater/tekton-catalog pull request #24
Opened 2022-11-30 15:30 UTC by mustafaStakater

2022-11-30 15:30 UTC, stakater-user commented
@mustafaStakater Validation Successful

2022-11-30 16:40 UTC, rasheedamir commented on clustertask/validate-environment/templates/clustertask.yaml
> +  - name: push-main-tag
@TehreemNisa wrong name?

2022-11-30 16:41 UTC, rasheedamir commented on clustertask/validate-environment/templates/clustertask.yaml
> +    - name: environmentName
ENVIRONMENT_NAME

2022-11-30 16:49 UTC, rasheedamir commented on clustertask/validate-environment/templates/clustertask.yaml
> +      Validate Helm Release Status of Tronodor Environment
@mustafaStakater should we use the word HelmRelease here? Wouldn't it be better we just use word Environment

2022-11-30 16:52 UTC, rasheedamir commented
@mustafaStakater did you manage to run and test it locally?

2022-11-30 17:00 UTC, rasheedamir commented on clustertask/validate-environment/templates/clustertask.yaml
> +          condition_type=$(echo $environmentStatus | jq -r '.resourceStatus.conditions[0].type')
@mustafaStakater why different naming convention here? Why adding _ here?

2022-11-30 17:00 UTC, rasheedamir commented
@mustafaStakater can you plz also add the test data? and explain the readme how to run and validate it locally?

2022-11-30 17:01 UTC, rasheedamir requested changes
Check the feedback

2022-12-01 06:24 UTC, mustafaStakater commented
@rasheedamir I wasnt able to test it out locally, I tried deploying the environment crd but for some reason it was continously discarding the status field because it is managed by openshift itself, i then moved on to deploying tronador but the initial setup was taking a lot of time, 
~I'll test it out on devtest for now~

2022-12-01 10:48 UTC, rasheedamir commented on clustertask/validate-environment/templates/clustertask.yaml
> +    - name: WAIT_TIME_FOR_RECONCILE
TIMEOUT

2022-12-05 21:05 UTC, rasheedamir commented
> @rasheedamir I wasnt able to test it out locally, I tried deploying the environment crd but for some reason it was continously discarding the status field because it is managed by openshift itself, i then moved on to deploying tronador but the initial setup was taking a lot of time, I'll test it out on devtest for now

as discussed this needs to be tested locally and then tests should be pushed as well in this repo

2022-12-13 11:04 UTC, AsfaMumtaz approved these changes

2022-12-13 11:46 UTC, rasheedamir approved these changes

2022-12-13 11:46 UTC, merged